### ISSUE TITLE
Deployment status not added when triggered on tag version.

### ISSUE THREAD

**Issue by ennioma** [CircleCI-Public/jira-connect-orb#53]
### Orb version

orbs:
  jira: circleci/jira@1.3.0

### What happened

I've a pipeline which is triggered when something is merged to develop.

When it happens we trigger a new workflow which tags a new version of our software.

<img width="1194" alt="Screenshot 2020-11-13 at 11 25 32" src="https://user-images.githubusercontent.com/2176586/99067743-207ea600-25a3-11eb-9f0a-aba629c25dc1.png">

As you can see, the flow is triggered on a specific tag.

And the **jira_notify** job is executed here:
<img width="1395" alt="Screenshot 2020-11-13 at 11 24 21" src="https://user-images.githubusercontent.com/2176586/99067857-515edb00-25a3-11eb-8006-c27f8514ba77.png">

That release include only one ticket which has been merged to develop, i.e. it's ABC-123 and that ticket name is included:
1. in the branch name which has been merged to develop
2. in one of the new commits merged to develop

This is the yml chunk where I've configured jira_notify:

```
      - base_checkout:
          name: Prod deploy
          post-steps:
            - jira/notify:
                environment_type: production
                job_type: deployment
                scan_commit_body: false
```

I've tried with both **scan_commit_body** = true and false.

### Expected behavior
The ticket ABC-123 is marked as deployed on JIRA

### Actual behavior
<img width="956" alt="Screenshot 2020-11-13 at 11 24 10" src="https://user-images.githubusercontent.com/2176586/99068031-a7cc1980-25a3-11eb-8ddf-a65196eed902.png">
