### ISSUE TITLE
Jira orb with Fastlane not working

### ISSUE THREAD

**Issue by nataliakuznetsova** [CircleCI-Public/jira-connect-orb#59]
### Orb version
1.3.0

### What happened
I am trying to integrate the orb for my build and release pipeline for an Android project. There is a job for build and test step. Adding "jira/notify" works well. 

In addition to that I am trying to add a "jira/notify" for a deployment. The job is triggered via fastlane lane. When inluding the command with default values, it works well, but when adding the job_type and environment_type it fails on CircleCI with error:

```
Cannot find a definition for command named notify

Error calling job: 'assemble_beta_apk_with_firebase'

Error calling workflow: 'assemble_beta_apk_with_firebase'
```

Here is the job definition, some parts are omitted. 

Configuration that works:
```
version: 2.1

orbs:
    jira: circleci/jira@1.3.0

...

  assemble_beta_apk_with_firebase:
    <<: *android_config
    environment:
    steps:
      - *checkout_code
      - *android_dependencies
      - run:
          name: Clean old APK's
          command: |
            cd workspace/App
            ./gradlew clean
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL firebase.tools | bash
      - run:
          name: Build beta APKs and upload to Firebase App Distribution
          command: |
            cd workspace/App
            bundle exec fastlane android distribute_branch_with_temp_version_name branch_name:${CIRCLE_BRANCH}`
      - jira/notify

...
```
Configuration that produced the error:

```
version: 2.1

orbs:
    jira: circleci/jira@1.3.0

...

  assemble_beta_apk_with_firebase:
    <<: *android_config
    environment:
    steps:
      - *checkout_code
      - *android_dependencies
      - run:
          name: Clean old APK's
          command: |
            cd workspace/App
            ./gradlew clean
      - run:
          name: Install Firebase CLI
          command: |
            curl -sL firebase.tools | bash
      - run:
          name: Build beta APKs and upload to Firebase App Distribution
          command: |
            cd workspace/App
            bundle exec fastlane android distribute_branch_with_temp_version_name branch_name:${CIRCLE_BRANCH}`
      - jira/notify:
          environment_type: testing
          job_type: deployment

...
```
