### ISSUE TITLE
circleci/jira@1.3.1 is not working correctly with alpine based images

### ISSUE THREAD

**Issue by andormarkus** [CircleCI-Public/jira-connect-orb#64]
Orb version: 1.3.1

### What happened
Based on our investigation the latest (1.3.1) as previous (1.3.0) version of this orb does not work together with alpine based docker images. Tested images: alpine:latest, hashicorp/terraform:latest

Working pipelines
```
jira:
    docker:
        -   image: cimg/base:stable
    steps:
        - jira/notify
```

Not working pipeline
```
jira:
    docker:
        -   image: alpine
    steps:
        - run: apk add --no-cache jq
        - run: apk add --no-cache curl
        - jira/notify
```

Error code
```
Curl failed with code 200. full response below.
{
  "name" : "James Bond",
  "login" : "agent007",
  "id" : "xxxxxx-xxxx-xxxx-xxxx-xxxxxx"
}
````
