### ISSUE TITLE
Jira Orb Requires an Unsafe PAT

### ISSUE THREAD

**Issue by RobbieMcKinstry** [CircleCI-Public/jira-connect-orb#66]
### Orb version

`1.3.1`

### What happened

The Jira orb requires a CircleCI personal access token (PAT) in the job's environment to run. This is insecure, because it means that anyone with access to the CircleCI job can act on behalf of the user.

Consider the following CCI configuration:

```yaml
version: 2.1

orbs:
  jira: circleci/jira@1.3.1

jobs:
  jira:
    docker:
      - image: cimg/base:2021.03
    steps:
      - jira/notify
      - echo $CIRCLE_TOKEN
workflows:
  main:
    jobs:
      - jira
``` 
In this example, I have set `$CIRCLE_TOKEN` to my Personal Access Token. 
Imagine this configuration is for an organization's repository. Suppose the line `echo $CIRCLE_TOKEN` was injected by an attacker who can access my organization's build logs. Then, they would gain access to my account via the PAT.

This is not an unreasonable situation; an angry coworker could gain access to my PAT and perform actions on my behalf, and it could prove challenging to procedure the audit log leading back to them.

Further, running this job even logs _who_ the PAT belongs to. See the image below for a example log.
<img width="677" alt="Screen Shot 2021-04-02 at 6 30 09 PM" src="https://user-images.githubusercontent.com/4955075/113458783-77193f00-93e1-11eb-96b0-54ae41074581.png">

That means an attack, by default, knows who they are targeting. It would be easy to remove that log line to obscure who the PAT belongs to, though the CCI API allows any PAT holder to identify themselves with an API call.

### Expected behavior

The Jira orb should access a Project API Token in addition to a PAT.

I understand that this project previously switched from using a Project API Token to a PAT, but I can't find documentation on _why_ that decision was made. Could you provide guidance on how to use this orb securely? With respect, it appears to be insecure by default, and I'm afraid I can't figure out how to secure my PAT or prevent exposing it.
