### ISSUE TITLE
jira orb throw error "At least one 'issueKeys' is required"

### ISSUE THREAD

**Issue by shinji3887** [CircleCI-Public/jira-connect-orb#68]
### Orb version

circleci/jira@1.3.1

### What happened

when i use circleci/jira@1.3.1, i got an error in the step "Update status in Atlassian Jira":
```bash
"shinji3887"
This job is passing, however another job in workflow is running
Results from Jira: 

{
  "acceptedBuilds": [],
  "rejectedBuilds": [
    {
      "key": {
        "pipelineId": "jiratest",
        "buildNumber": 13
      },
      "errors": [
        {
          "message": "At least one 'issueKeys' is required"
        }
      ]
    }
  ],
  "unknownIssueKeys": []
}
```
and i use the example yml in this url : [https://circleci.com/developer/orbs/orb/circleci/jira?version=1.3.1](https://circleci.com/developer/orbs/orb/circleci/jira?version=1.3.1) like:
```yaml
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify
```
and my jobs in circle-ci looks work well
![image](https://user-images.githubusercontent.com/38430452/117322133-505a9680-aec0-11eb-8e31-9e57aaec9bdb.png)
please help me.

**Comment by nbialostosky** [comment]
Hi @shinji3887 !

By default, the Jira Orb has an issue regex of `[A-Z]{2,30}-[0-9]+` -- which in this scenario doesn't match the branch you have `JF1-13`. 

Can you try overriding your regex to `[A-Z]{2,30}[0-9]-[0-9]+` and see if the Jira orb correctly reports the status back to the issue?

As an example:

```
jobs:
  build:
    docker:
      - image: 'circleci/node:10'
    steps:
      - run: echo "hello"
orbs:
  jira: circleci/jira@1.3.1
version: 2.1
workflows:
  build:
    jobs:
      - build:
          post-steps:
            - jira/notify:
                issue_regexp: '[A-Z]{2,30}[0-9]-[0-9]+'
```
