### ISSUE TITLE
Jira Connect Orb fails on Windows executors

### ISSUE THREAD

**Issue by kevin--** [CircleCI-Public/jira-connect-orb#73]
### Orb version
circleci/jira@1.3.1

### What happened

Windows executor's default shell is `powershell.exe`, so the jira scripts expecting bash fail immediately. `bash.exe` is available on these machines, but I can't figure out how to specify the shell to use with the orb.

Minimal example

```
version: 2.1

orbs:
  windows: circleci/windows@2.4.1
  jira: circleci/jira@1.3.1

jobs:
  build-win:
    executor:
      name: windows/default
    steps:
      - run:
          command: echo dummy step

workflows:
  build-all:
    jobs:
      - build-win:
          post-steps:
            - jira/notify
```

### Expected behavior
`jira/notify` works out of the box on Windows executors
