### ISSUE TITLE
error: scan is not defined

### ISSUE THREAD

**Issue by alfred-soroush** [CircleCI-Public/jira-connect-orb#74]
### Orb version

1.3.1

### What happened

Here is the circle config

```
workflows:
  build-deploy:
    jobs:
      - build:
          post-steps:
            - jira/notify
      - build-docker-image:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
            - build-docker-image
          filters:
            branches:
              only: develop
          post-steps:
            - jira/notify:
                job_type: deployment
```
The jira/notify job with type deployment fails with the following error:

```
error: scan is not defined
[.all_commit_details[].subject | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [.all_commit_details[].branch | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [if .branch then .branch else "" end | scan("([A-Z]{2,30}-[0-9]+)")  | . [] ] + [if false then .all_commit_details[].body else "" end | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ]                                 error: scan is not defined
[.all_commit_details[].subject | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [.all_commit_details[].branch | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [if .branch then .branch else "" end | scan("([A-Z]{2,30}-[0-9]+)")  | . [] ] + [if false then .all_commit_details[].body else "" end | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ]                                                                                                          error: scan is not defined
[.all_commit_details[].subject | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [.all_commit_details[].branch | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [if .branch then .branch else "" end | scan("([A-Z]{2,30}-[0-9]+)")  | . [] ] + [if false then .all_commit_details[].body else "" end | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ]                                                                                                                                                                                          error: scan is not defined
[.all_commit_details[].subject | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [.all_commit_details[].branch | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ] + [if .branch then .branch else "" end | scan("([A-Z]{2,30}-[0-9]+)")  | . [] ] + [if false then .all_commit_details[].body else "" end | scan("([A-Z]{2,30}-[0-9]+)")   | .[] ]                                                                                                                                                                                                                                                                                           4 compile errors

Exited with code exit status 3
```

### Expected behavior

job should pass.
