### ISSUE TITLE
Deployments do not appear in Jira when using a `post-step`

### ISSUE THREAD

**Issue by krisleech** [CircleCI-Public/jira-connect-orb#81]
### Orb version

1.3.1

### What happened

We have a deploy job which has a post step to notify jira of a deployment:

```yaml
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
          post-steps:
            - jira/notify:
                job_type: deployment
                environment_type: production
```

We get a success message back from Jira:

```json
{
  "unknownIssueKeys": [],
  "acceptedBuilds": [
    {
      "pipelineId": "booking-system",
      "buildNumber": 613
    }
  ],
  "rejectedBuilds": []
}


Success!
```

![Screenshot 2022-02-16 at 12 12 54](https://user-images.githubusercontent.com/66143/154262337-fe63c9ac-ac40-46cd-aba4-572440a2c758.png)

But nothing appears on the Jira deployment page and the "cycle time report" says "more data required".

### Expected behavior

We see the deployments in Jira.

Note that notifying of builds works just fine.

When the job type is deployment the docs say: "Note that Deployments require additional details", are we missing anything? I'm not sure what the additional details are.

**Comment by krisleech** [comment]
Update it seems to work if we move from a `post-step` to a `step`:

```
deploy:
  steps:
    - jira/notify:
        job_type: deployment
        environment_type: production

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - deploy:
          filters:
            branches:
              only: main
```

The result from Jira is:

```
This job is passing, however another job in workflow is running
Update Jira with status: successful for 622
Results from Jira: 
ERROR: unknown association
{
  "unknownIssueKeys": [],
  "unknownAssociations": [
    {
      "values": [
        ""
      ],
      "associationType": "serviceIdOrKeys"
    }
  ],
  "acceptedDeployments": [
    {
      "pipelineId": "booking-system",
      "environmentId": "...",
      "deploymentSequenceNumber": 622
    }
  ],
  "rejectedDeployments": []
}

```

Not sure if the error is a problem. I do see something on the deployments page in Jira now.
